import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { AdminPageHeader } from "@/features/admin/shared/components/page-header";
import { idSchema } from "@/features/admin/shared/schemas";
import { getModerationDetail } from "@/features/admin/moderation/server/moderation-service";
import { ReportStatusAction } from "@/features/admin/moderation/components/report-status-action";

export default async function ModerationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const parsed = idSchema.safeParse((await params).id);
  if (!parsed.success) notFound();
  const resume = await getModerationDetail(parsed.data).catch(() => notFound());
  const views = resume.events.filter(event => event.type === "VIEW").length;
  const downloads = resume.events.filter(event => event.type === "DOWNLOAD").length;
  return <><AdminPageHeader eyebrow="Moderation case" title={resume.title} description={`Owned by ${resume.user.name || resume.user.email}. Private section content is intentionally excluded.`} /><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-6"><Card className="p-5"><h2 className="font-semibold">Public metadata</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted-foreground">State</dt><dd className="mt-1"><Badge>{resume.moderationHiddenAt ? "MODERATED" : resume.isPublic ? "PUBLIC" : "PRIVATE"}</Badge></dd></div><div><dt className="text-xs text-muted-foreground">Template</dt><dd className="mt-1">{resume.template}</dd></div><div><dt className="text-xs text-muted-foreground">Recent views</dt><dd className="mt-1">{views}</dd></div><div><dt className="text-xs text-muted-foreground">Recent downloads</dt><dd className="mt-1">{downloads}</dd></div></dl>{resume.moderationReason && <div className="mt-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-700 dark:text-rose-300">{resume.moderationReason}</div>}</Card><Card className="p-5"><h2 className="font-semibold">Reports</h2><div className="mt-4 space-y-3">{resume.reports.map(report => <div key={report.id} className="rounded-xl border border-border p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{report.reason}</p><Badge>{report.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{report.details || "No additional details."}</p><p className="mt-2 text-[10px] text-muted-foreground">{report.createdAt.toLocaleString()}</p><ReportStatusAction resumeId={resume.id} reportId={report.id} currentStatus={report.status} /></div>)}{!resume.reports.length && <p className="text-sm text-muted-foreground">No reports have been submitted.</p>}</div></Card></div><Card className="p-5"><h2 className="font-semibold">Moderation history</h2><div className="mt-4 space-y-3">{resume.moderation.map(action => <div key={action.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">{action.action.replaceAll("_", " ")}</p><Badge>{action.createdAt.toLocaleDateString()}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{action.reason || "No reason recorded."}</p><p className="mt-2 text-[10px] text-muted-foreground">{action.actor?.name || action.actor?.email || "System"} · {action.createdAt.toLocaleString()}</p></div>)}{!resume.moderation.length && <p className="text-sm text-muted-foreground">No moderation action has been taken.</p>}</div></Card></div></>;
}
